"""empty message

Revision ID: 80599072082e
Revises: 30784b7dd617
Create Date: 2017-01-21 20:32:28.883704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80599072082e'
down_revision = '30784b7dd617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('record', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record'], ['exchange_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_image_name'), 'record_image', ['name'], unique=False)
    op.drop_table('sqlite_stat1')
    op.drop_table('sqlite_stat4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_record_image_name'), table_name='record_image')
    op.drop_table('record_image')
    # ### end Alembic commands ###
