"""empty message

Revision ID: ed8d29f0e0ea
Revises: 
Create Date: 2017-01-22 00:30:19.916252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8d29f0e0ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('social_id', sa.String(length=64), server_default='err', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_table('user_want_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_want_list_name'), 'user_want_list', ['name'], unique=False)
    op.create_table('book_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('book_type', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('target_place', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_exchanged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['create_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_book_record_author'), 'book_record', ['author'], unique=False)
    op.create_index(op.f('ix_book_record_book_type'), 'book_record', ['book_type'], unique=False)
    op.create_index(op.f('ix_book_record_description'), 'book_record', ['description'], unique=False)
    op.create_index(op.f('ix_book_record_language'), 'book_record', ['language'], unique=False)
    op.create_index(op.f('ix_book_record_name'), 'book_record', ['name'], unique=False)
    op.create_index(op.f('ix_book_record_service_type'), 'book_record', ['service_type'], unique=False)
    op.create_index(op.f('ix_book_record_target_place'), 'book_record', ['target_place'], unique=False)
    op.create_table('exchange_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('from_star', sa.Integer(), nullable=True),
    sa.Column('to_star', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('record', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record'], ['book_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_stat1')
    op.drop_table('sqlite_stat4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_stat4',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('neq', sa.NullType(), nullable=True),
    sa.Column('nlt', sa.NullType(), nullable=True),
    sa.Column('ndlt', sa.NullType(), nullable=True),
    sa.Column('sample', sa.NullType(), nullable=True)
    )
    op.create_table('sqlite_stat1',
    sa.Column('tbl', sa.NullType(), nullable=True),
    sa.Column('idx', sa.NullType(), nullable=True),
    sa.Column('stat', sa.NullType(), nullable=True)
    )
    op.drop_table('record_image')
    op.drop_table('exchange_record')
    op.drop_index(op.f('ix_book_record_target_place'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_service_type'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_name'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_language'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_description'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_book_type'), table_name='book_record')
    op.drop_index(op.f('ix_book_record_author'), table_name='book_record')
    op.drop_table('book_record')
    op.drop_index(op.f('ix_user_want_list_name'), table_name='user_want_list')
    op.drop_table('user_want_list')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
